#!/bin/bash

if [[ $IMAGE_NAME == *"dev-3.7" ]]; then
  docker build -t $IMAGE_NAME --build-arg VARIANT=3.7
elif [[ $IMAGE_NAME == *"dev-3.8" ]]; then
  docker build -t $IMAGE_NAME --build-arg VARIANT=3.8
elif [[ $IMAGE_NAME == *"dev-3.9" ]]; then
  docker build -t $IMAGE_NAME --build-arg VARIANT=3.9
elif [[ $IMAGE_NAME == *"cuda" ]]; then
  docker build -t $IMAGE_NAME --build-arg HARDWARE=cuda
elif [[ $IMAGE_NAME == *"cucpuda" ]]; then
  docker build -t $IMAGE_NAME --build-arg HARDWARE=cpu
fi
