name: Docker
# https://www.docker.com/blog/first-docker-github-action-is-here
# https://github.com/docker/build-push-action
# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches:
      - 'master'
      - 'main'
  release:
    types:
      - created
  pull_request:
    branches:
      - 'master'
      - 'main'


jobs:
  build-docker:
    runs-on: ubuntu-20.04
    # need this to patch around git. See https://github.com/actions/checkout/issues/335#issuecomment-827903708
    # container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        accelerator: ['cpu', 'cuda']

    steps:
      # need this to patch around git. See https://github.com/actions/checkout/issues/335#issuecomment-827903708
      # - name: Obtain Latest Git ONLY within container for checkout
      #   run: apk add git --update-cache
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      - name: Checkout Git repository
        run: git clone  git@github.com:${{ github.repository }} my_repo && cd my_repo && git checkout ${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
          tags: |
            type=pep440,pattern={{version}}-${{ matrix.accelerator }}
            type=raw,value=latest-${{ matrix.accelerator }}

      - name: Build
        # publish master/release
        uses: docker/build-push-action@v2
        with:
          file: dockers/Dockerfile
          push: false # ${{ github.event_name != 'pull_request' }}
          # arm64 has issues compiling SimpleITK from source
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          build-args: |
            HARDWARE=${{ matrix.accelerator }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            maintainer=justusschock
            ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

        timeout-minutes: 50
